name: Dash App CI

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Test the app using Docker
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image for testing
      - name: Build Docker image for testing
        run: docker build -t casschang02/ml-125002-a3 -f Dockerfile .

      # Run tests inside the Docker container
      - name: Run tests in Docker
        run: docker run casschang02/ml-125002-a3 pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Build only after tests pass
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image for the app
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/casschang02/ml-125002-a3:latest -f Dockerfile .

      # Push the image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/casschang02/ml-125002-a3:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ml.brain.cs.ait.ac.th  # Final destination server
          username: ${{ secrets.USERNAME }}  # Your username for the final server
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your private key
          password: ${{ secrets.REMOTE_PASSWORD }}
          proxy_host: bazooka.cs.ait.ac.th  # Jump host
          proxy_username: st125002  # Your username for the jump host
          proxy_key: ${{ secrets.PROXY_KEY }}  # Your key for the jump host
          script: |
            docker pull casschang02/ml-st125002-a3:latest
            docker compose -f docker-compose.yaml down --remove-orphans
            docker compose -f docker-compose.yaml up -d
